# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_paste <- function() {
    .Call('_Rcppzhuoer_test_paste', PACKAGE = 'Rcppzhuoer')
}

as_tibble <- function(l) {
    .Call('_Rcppzhuoer_as_tibble', PACKAGE = 'Rcppzhuoer', l)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_Rcppzhuoer_RcppExport_registerCCallable', PACKAGE = 'Rcppzhuoer')
})
